use_frameworks!

platform :ios, '8.0'

target 'SHLoging_Example' do
  pod 'SHLoging', :path => '../'
  pod 'SHNetworking', :path => '../../SHNetworking'
  target 'SHLoging_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    
  end
end
